version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todoapi_postgres
    environment:
      POSTGRES_DB: todoapi
      POSTGRES_USER: todoapi_user
      POSTGRES_PASSWORD: todoapi_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todoapi_user -d todoapi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
